title: Oficina Framework
theme: jekyll-theme-cayman
email: lucas.samuel2002@gmail.com
description: >
  Oficina is a multiplatform game framework for Linux and Windows.
  It uses everything C++ has to offer, plus adds the ability to run
  Scheme as scripting language. Oficina is prepared for modern game
  development and provides tools to ease the usage of more complicated
  structures and features.
twitter_username: luksamuk
github_username: luksamuk