Oficina Framework: OficinaFramework::IOSystem::ScriptTools Class Reference
OficinaFramework::IOSystem::ScriptTools Class Reference
A class for opening and loading Gongly Script data. Works since Gongly Script v1.0.
#include <IOSystem.hpp>
Public Member Functions
ScriptTools (ScriptStream *stream)
Creates a ScriptTools and opens a specific script.
ScriptTools ()
Creates a new ScriptTools with no file loaded.
~ScriptTools ()
Disposes the ScriptTools.
void LoadScript (ScriptStream *stream)
Loads a specific script.
void UnloadScript ()
Unloads a script, if loaded.
bool IsScriptLoaded ()
Checks for loaded scripts.
uint16_t GetEntityID ()
Retrieves the next entity's ID and checks for EOF.
int GetInt ()
Retrieves an INT (32-bit signed int) from the loaded script stream.
float GetFloat ()
Retrieves a FLOAT (16-bit float) from the loaded script stream.
double GetDouble ()
Retrieves a DOUBLE (32-bit float) from the loaded script stream.
bool GetBool ()
Retrieves a BOOL (8-bit int, translated to C++ bool type) from the loaded script stream.
char * GetString ()
Retrieves a STRING (32-bit unsigned int with number of characters + n_characters * signed char, translated to C++ char* type) from the loaded script stream.
vec2 GetVec2 ()
Retrieves a VEC2 (2 * 16-bit float, translated to Oficina's vec2 type) from the loaded script stream.
vec3 GetVec3 ()
Retrieves a VEC3 (3 * 16-bit float, translated to Oficina's vec3 type) from the loaded script stream.
Color4 GetVec4 ()
Retrieves a VEC4 (4 * 16-bit float, translated to Oficina's Color4 type) from the loaded script stream.
byte GetByte ()
Retrieves a BYTE (8-bit unsigned int, byte) from the loaded script stream.
word GetWord ()
Retrieves a WORD (16-bit unsigned int, word) from the loaded script stream.
dword GetDword ()
Retrieves a DWORD (32-bit unsigned int, dword) from the loaded script stream.
qword GetQword ()
Retrieves a QWORD (64-bit unsigned int, qword) from the loaded script stream.
byte_s GetByte_s ()
Retrieves a BYTE_S (8-bit signed int, byte_s) from the loaded script stream.
word_s GetWord_s ()
Retrieves a WORD_S (16-bit signed int, word_s) from the loaded script stream.
dword_s GetDword_s ()
Retrieves a DWORD_S (32-bit signed int, dword_s) from the loaded script stream.
qword_s GetQword_s ()
Retrieves a QWORD_S (64-bit signed int, qword_s) from the loaded script stream.
bool IsEOF ()
Checks if script has reached EOF manually.
qword_s ToEOF ()
Gets the number of bytes until EOF.
Detailed Description
A class for opening and loading Gongly Script data. Works since Gongly Script v1.0.
Constructor & Destructor Documentation
ScriptTools() [1/2]
OficinaFramework::IOSystem::ScriptTools::ScriptTools (ScriptStream * stream)
Creates a ScriptTools and opens a specific script.
Parameters
stream Byte stream containing the script data.
ScriptTools() [2/2]
OficinaFramework::IOSystem::ScriptTools::ScriptTools () inline
Creates a new ScriptTools with no file loaded.
References OficinaFramework::IOSystem::IsInitialized(), OficinaFramework::IOSystem::SwapEndianness16(), OficinaFramework::IOSystem::SwapEndianness32(), OficinaFramework::IOSystem::SwapEndianness64(), OficinaFramework::IOSystem::SwapEndiannessD(), and OficinaFramework::IOSystem::SwapEndiannessF().
~ScriptTools()
OficinaFramework::IOSystem::ScriptTools::~ScriptTools ()
Disposes the ScriptTools.
Member Function Documentation
GetBool()
bool OficinaFramework::IOSystem::ScriptTools::GetBool ()
Retrieves a BOOL (8-bit int, translated to C++ bool type) from the loaded script stream.
GetByte()
byte OficinaFramework::IOSystem::ScriptTools::GetByte ()
Retrieves a BYTE (8-bit unsigned int, byte) from the loaded script stream.
GetByte_s()
byte_s OficinaFramework::IOSystem::ScriptTools::GetByte_s ()
Retrieves a BYTE_S (8-bit signed int, byte_s) from the loaded script stream.
GetDouble()
double OficinaFramework::IOSystem::ScriptTools::GetDouble ()
Retrieves a DOUBLE (32-bit float) from the loaded script stream.
GetDword()
dword OficinaFramework::IOSystem::ScriptTools::GetDword ()
Retrieves a DWORD (32-bit unsigned int, dword) from the loaded script stream.
GetDword_s()
dword_s OficinaFramework::IOSystem::ScriptTools::GetDword_s ()
Retrieves a DWORD_S (32-bit signed int, dword_s) from the loaded script stream.
GetEntityID()
uint16_t OficinaFramework::IOSystem::ScriptTools::GetEntityID ()
Retrieves the next entity's ID and checks for EOF.
Returns
0 for end-of-file, or the ID of the entity. First valid value is 1.
GetFloat()
float OficinaFramework::IOSystem::ScriptTools::GetFloat ()
Retrieves a FLOAT (16-bit float) from the loaded script stream.
GetInt()
int OficinaFramework::IOSystem::ScriptTools::GetInt ()
Retrieves an INT (32-bit signed int) from the loaded script stream.
GetQword()
qword OficinaFramework::IOSystem::ScriptTools::GetQword ()
Retrieves a QWORD (64-bit unsigned int, qword) from the loaded script stream.
GetQword_s()
qword_s OficinaFramework::IOSystem::ScriptTools::GetQword_s ()
Retrieves a QWORD_S (64-bit signed int, qword_s) from the loaded script stream.
GetString()
char* OficinaFramework::IOSystem::ScriptTools::GetString ()
Retrieves a STRING (32-bit unsigned int with number of characters + n_characters * signed char, translated to C++ char* type) from the loaded script stream.
GetVec2()
vec2 OficinaFramework::IOSystem::ScriptTools::GetVec2 ()
Retrieves a VEC2 (2 * 16-bit float, translated to Oficina's vec2 type) from the loaded script stream.
GetVec3()
vec3 OficinaFramework::IOSystem::ScriptTools::GetVec3 ()
Retrieves a VEC3 (3 * 16-bit float, translated to Oficina's vec3 type) from the loaded script stream.
GetVec4()
Color4 OficinaFramework::IOSystem::ScriptTools::GetVec4 ()
Retrieves a VEC4 (4 * 16-bit float, translated to Oficina's Color4 type) from the loaded script stream.
GetWord()
word OficinaFramework::IOSystem::ScriptTools::GetWord ()
Retrieves a WORD (16-bit unsigned int, word) from the loaded script stream.
GetWord_s()
word_s OficinaFramework::IOSystem::ScriptTools::GetWord_s ()
Retrieves a WORD_S (16-bit signed int, word_s) from the loaded script stream.
IsEOF()
bool OficinaFramework::IOSystem::ScriptTools::IsEOF ()
Checks if script has reached EOF manually.
IsScriptLoaded()
bool OficinaFramework::IOSystem::ScriptTools::IsScriptLoaded ()
Checks for loaded scripts.
Returns
Whether any script is loaded or not.
LoadScript()
void OficinaFramework::IOSystem::ScriptTools::LoadScript (ScriptStream * stream)
Loads a specific script.
Parameters
stream Byte stream containing the script data.
ToEOF()
qword_s OficinaFramework::IOSystem::ScriptTools::ToEOF ()
Gets the number of bytes until EOF.
Returns
Number of bytes until EOF is reached.
UnloadScript()
void OficinaFramework::IOSystem::ScriptTools::UnloadScript ()
Unloads a script, if loaded.
The documentation for this class was generated from the following file:
IOSystem.hpp