Oficina Framework: OficinaFramework::EntitySystem::DrawableEntity Class Reference
OficinaFramework::EntitySystem::DrawableEntity Class Reference abstract
Abstract class representing an entity that can be drawn onscreen.
#include <EntitySystem.hpp>
Public Member Functions
virtual ~DrawableEntity ()
Destructor for the drawable entity.
virtual void Initialize ()=0
Initializes the logic of the drawable entity.
virtual void Update ()=0
Updates the drawable entity on runtime.
virtual void LoadContent ()=0
Loads content for the drawable entity, such as textures.
virtual void UnloadContent ()=0
Unloads content for the drawable entity, such as textures.
virtual void Draw ()=0
Draws the drawable entity.
Color4 GetColor () const
Gets the internal color of the drawable entity.
void SetColor (Color4 c)
Sets the internal color of the drawable entity.
float GetDrawDepth () const
Gets the draw depth for drawing.
void SetDrawDepth (float depth)
Sets the draw depth.
float GetScale () const
Gets the scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
void SetScale (float value)
Sets the scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
RenderingSystem::RenderProperty GetOrientation () const
Gets object orientation. Implemented as per Gongly Script standard (0.2) (2014).
void SetOrientation (RenderingSystem::RenderProperty value)
Sets object orientation. Implemented as per Gongly Script standard (0.2) (2014).
DrawableEntityCollection * GetParent ()
Gets entity collection that manages this entity.
void SetParent (DrawableEntityCollection *ec)
Sets a pointer to the entity collection that manages this entity.
Public Member Functions inherited from OficinaFramework::EntitySystem::Entity
virtual ~Entity ()
Destructor for the entity.
vec2 GetPosition () const
Gets the position of the entity.
void SetPosition (vec2 Position)
Sets the position of the entity.
float GetAngle () const
Gets the angle of the entity.
void SetAngle (float Angle)
Sets the angle of the entity.
std::string GetName () const
Gets the name of the entity.
void SetName (std::string name)
Sets the name of the entity.
bool GetProperty (byte ID) const
Gets the state of a single property on the properties mask.
void SetProperty (byte ID, bool state)
Sets the state of a single property on the properties mask.
qword GetProperties () const
Gets the whole properties mask of the entity.
void SetProperties (qword newmask)
Sets the whole properties mask of the entity.
EntityCollection * GetParent ()
Gets entity collection that manages this entity.
void SetParent (EntityCollection *ec)
Sets a pointer to the entity collection that manages this entity.
bool IsMarkedForRemoval ()
Gets if the current entity is marked for removal.
void RemoveMe ()
Marks the current entity for removal.
Protected Attributes
Color4 m_color
Internal color of the entity. Can be used for color blending. Implemented as per Gongly Script standard (2014).
float m_depth = 0.0f
Internal depth for using on draw order of a DrawableEntityCollection. Implemented as per Gongly Script standard (2014).
float m_scale = 1.0f
Internal scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
RenderingSystem::RenderProperty m_orientation = RenderingSystem::RENDER_NORMALLY
Internal orientation for object drawing. Implemented as per Gongly Script standard (0.2) (2014).
Protected Attributes inherited from OficinaFramework::EntitySystem::Entity
std::string m_name
Name of the entity.
vec2 m_position
Position of the entity, as per Gongly Script standard (2014).
float m_angle = 0.0f
Angle of the entity, as per Gongly Script standard (2014).
qword m_properties = 0x0000000000000000u
A set of 64 boolean properties fo the entity, as per Gongly Script standard (2014).
Detailed Description
Abstract class representing an entity that can be drawn onscreen.
Constructor & Destructor Documentation
~DrawableEntity()
virtual OficinaFramework::EntitySystem::DrawableEntity::~DrawableEntity () inline virtual
Destructor for the drawable entity.
References OficinaFramework::EntitySystem::Entity::GetParent(), OficinaFramework::EntitySystem::Entity::Initialize(), OficinaFramework::EntitySystem::Entity::SetParent(), and OficinaFramework::EntitySystem::Entity::Update().
Member Function Documentation
Draw()
virtual void OficinaFramework::EntitySystem::DrawableEntity::Draw () pure virtual
Draws the drawable entity.
GetColor()
Color4 OficinaFramework::EntitySystem::DrawableEntity::GetColor () const
Gets the internal color of the drawable entity.
Returns
Internal color used for effects such as color blending, etc.
GetDrawDepth()
float OficinaFramework::EntitySystem::DrawableEntity::GetDrawDepth () const
Gets the draw depth for drawing.
Returns
Current draw depth.
GetOrientation()
RenderingSystem::RenderProperty OficinaFramework::EntitySystem::DrawableEntity::GetOrientation () const
Gets object orientation. Implemented as per Gongly Script standard (0.2) (2014).
Returns
Object orientation in rendering property form.
GetParent()
DrawableEntityCollection* OficinaFramework::EntitySystem::DrawableEntity::GetParent ()
Gets entity collection that manages this entity.
Returns
A pointer to the entity collection that manages this entity.
GetScale()
float OficinaFramework::EntitySystem::DrawableEntity::GetScale () const
Gets the scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
Returns
Scale value of the entity.
Initialize()
virtual void OficinaFramework::EntitySystem::DrawableEntity::Initialize () pure virtual
Initializes the logic of the drawable entity.
Implements OficinaFramework::EntitySystem::Entity.
LoadContent()
virtual void OficinaFramework::EntitySystem::DrawableEntity::LoadContent () pure virtual
Loads content for the drawable entity, such as textures.
SetColor()
void OficinaFramework::EntitySystem::DrawableEntity::SetColor (Color4 c)
Sets the internal color of the drawable entity.
Parameters
c Internal color to be used for effects such as color blending, etc.
SetDrawDepth()
void OficinaFramework::EntitySystem::DrawableEntity::SetDrawDepth (float depth)
Sets the draw depth.
Parameters
depth Draw depth order to be given to this DrawableEntity. A smaller or negative depth means earlier drawing.
SetOrientation()
void OficinaFramework::EntitySystem::DrawableEntity::SetOrientation (RenderingSystem::RenderProperty value)
Sets object orientation. Implemented as per Gongly Script standard (0.2) (2014).
Parameters
value Desired orientation to be set.
SetParent()
void OficinaFramework::EntitySystem::DrawableEntity::SetParent (DrawableEntityCollection * ec)
Sets a pointer to the entity collection that manages this entity.
Parameters
ec DrawableEntityCollection that manages this entity.
Attention
This method is automatically used when adding the entity to a collection. Use at your own risk.
SetScale()
void OficinaFramework::EntitySystem::DrawableEntity::SetScale (float value)
Sets the scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
Parameters
value Desired value to be set.
UnloadContent()
virtual void OficinaFramework::EntitySystem::DrawableEntity::UnloadContent () pure virtual
Unloads content for the drawable entity, such as textures.
Update()
virtual void OficinaFramework::EntitySystem::DrawableEntity::Update () pure virtual
Updates the drawable entity on runtime.
Implements OficinaFramework::EntitySystem::Entity.
Member Data Documentation
m_color
Color4 OficinaFramework::EntitySystem::DrawableEntity::m_color protected
Internal color of the entity. Can be used for color blending. Implemented as per Gongly Script standard (2014).
m_depth
float OficinaFramework::EntitySystem::DrawableEntity::m_depth = 0.0f protected
Internal depth for using on draw order of a DrawableEntityCollection. Implemented as per Gongly Script standard (2014).
m_orientation
RenderingSystem::RenderProperty OficinaFramework::EntitySystem::DrawableEntity::m_orientation = RenderingSystem::RENDER_NORMALLY protected
Internal orientation for object drawing. Implemented as per Gongly Script standard (0.2) (2014).
m_scale
float OficinaFramework::EntitySystem::DrawableEntity::m_scale = 1.0f protected
Internal scale value for object size. Implemented as per Gongly Script standard (0.2) (2014).
The documentation for this class was generated from the following file:
EntitySystem.hpp